version: '3.8'

services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - app-php

  pgsql:
    
    image: postgres:10
    container_name: pgsql
    ports: 
      - 5433:5432
    expose:
      - 5432
    volumes:
      - ./storage/db_psql:/var/lib/postgres
    environment:
     
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=admin
    networks:
      - app-php
  
  app_adminer:
    image: adminer
    container_name: app_adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=pgsql
      - ADMINER_DESIGN=price
    networks:
      - app-php

networks:
  app-php: